### ISSUE TITLE
Uncaught ReflectionException: Class template does not exist

### ISSUE THREAD

**Issue by NorbertFox** [TobyMaxham/yuttamf#1]
_Uncaught ReflectionException: Class template does not exist_

Diesen Fehler bekommt man, wenn man `$app->start()` nicht ausführt.
In der Dokumentation ist angegeben, dass es auch ohne funktioniert.

**Comment by riddg** [comment]
Thanks for the presentation on last weekend.
This code:
```php
app()->route()->get('/', function() {
    return app()->view('index.html');
});
```
dont work. It tells me `Class template does not exist`

Also i habe to execute `echo app()->route()->invoke()`. How does dis work?
